Manta signer
Manta-Network/manta-api pull request #23
Opened 2021-08-09 18:23 UTC by Kevingislason

2021-08-24 00:35 UTC, stechu commented
Can you add a short description (possibly in bullet points) covers the design of the changes?

2021-08-24 01:04 UTC, stechu requested changes
LGTM in general. Have some minor comments here.
Also, please add a comment string for each function (at least all public ones). The comment string starts from `///`

2021-09-04 04:46 UTC, Kevingislason commented on src/signer/hd_wallet.rs
> +
Looks consistent to me, not sure what you mean. What am I missing?

2021-09-04 04:58 UTC, Kevingislason commented on src/signer/params.rs
> +	pub asset_1_value: AssetBalance,
Yeah, `asset_1_*` is definitely vague, good call. Went with `sender_asset_1_*`, I think that is maximally unambiguous.

2021-09-04 05:09 UTC, Kevingislason commented on src/signer/payload_gen.rs
> +pub struct MantaUIAsset {
I agree that the current name should be changed. But future wallet designs might store different asset data (e.g. secret keys instead of keypaths).

A bit wordy, but how do you like `MantaSignerInputAsset`?

2021-09-08 23:08 UTC, bhgomes commented
Closing this in favor of #27.

2021-09-08 23:08 UTC, closed without merging